name: To Exe

on:
  push:
    branches: 
      - main
      - develop
      - debug
      - CI-test
  pull_request:
    branches:    
      - develop

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: skywalkerctu/pyinstaller-action@v1.2.1
        with:
          python_ver: '3.12.7'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'EDCM'